### ISSUE TITLE
Support define(['a', 'b'], fn(a)... -> var a=require('a'); require('b');

### ISSUE THREAD

**Issue by popham** [millermedeiros/nodefy#10]
Currently, the mentioned define yields `var a = require('a');`.  Module `b` loads under AMD, but vanishes under nodefy.  Pull request welcome?

**Comment by millermedeiros** [comment]
Yes! I would love a PR!

**Comment by popham** [comment]
I've published a fork to npm as nfy that incorporates the pull request. Thanks for 98% of the work.
