### ISSUE TITLE
Globstar as described in README dumps a single file, ignores the rest

### ISSUE THREAD

**Issue by popham** [millermedeiros/nodefy#11]
On 64-bit Archlinux under bash, I run

```
shopt -s globstar
nodefy -o output dir1/**.js
```

I get a single file in output, regardless of how many files are under dir1.  Am I doing something wrong?

**Comment by millermedeiros** [comment]
weird.. maybe [glob](http://npmjs.org/package/glob) `~3.1.14` doesn't work well on Archlinux..

**Comment by popham** [comment]
Playing around, `ls **/*.is` works as expected, but still nothing from nodefy.  This is confirmed to work properly on some other platform?

**Comment by popham** [comment]
Whoops.  Nodefy is interpreting globs internally.  I have to hide the glob from my shell.

Weirdness: `nodefy -o output ./a.js` -> `output/a.js`, while `nodefy -o output a.js` -> `output/ajs`.  The behavior belongs to Glob and/or Minimatch.
