### ISSUE TITLE
Circular importing broken because of `module.exports = {...}` instead of `exports.k1 = obj.k1; ...`

### ISSUE THREAD

**Issue by popham** [millermedeiros/nodefy#12]
I've got something analogous to the following:

a.js:

```
define(['./b'], function (b) {
    return { a : function (k) { return k === 10 ? 11 : b.b(k+1); } };
});
```

b.js:

```
define(['./a'], function (a) {
    return { b : function (i) { console.log(i); a.a(i); } };
});
```

This code nodefies as

a.js:

```
var b = require('./b');
    module.exports = {a : function (k) { return k === 10 ? 11 : b.b(k+1); } };
```

b.js:

```
var a = require('./a');
    module.exports = {b : function (i) { console.log(i); a.a(i); } };
```

From my uses of curljs and requirejs,I understand that an AMD loader will construct two objects before running either factory function.  Merging the factory function results into these predefined objects allows circular references to get resolved.  By returning a non-object from a factory function, bad things can happen with circular references.

I understand Node's `require` by analogy.  Assigning to `module.exports` is analogous to returning the non-object.  The above demonstrates how circular references that work under AMD no longer work post-Nodefy.

I think factory functions that return an object should have that object's members merged onto `exports` instead of assigning the object to `module.exports`.

**Comment by popham** [comment]
I'm putting together a pull request on this issue.  My driving use case is `return { a:someFn};`, which I feel maps to `exports.a = someFn;` without introducing any strange edge cases.  Just curious, is a runtime check justified for something like

```
define([], function () {
    var k = {};
    k.a = someFn;
    return k;
});
```

Or is this sort of thing the start of unwanted bloat in Nodefy?

**Comment by millermedeiros** [comment]
circular dependencies are tricky.. if you have them you should really be using the special dependency `exports`, like:

``` js
require(['exports', 'b'], function(exports, b) {
  exports.a = function() {
    // ...
  };
});
```

more about circular deps on the RequireJS documentation: http://requirejs.org/docs/api.html#circular

**Comment by popham** [comment]
I always figured that the CommonJS-like part of the AMD spec was built so that I could wrap a Node module with `define(function (require, exports, module) { ... })` and have it just work.  I guess I like the `exports` form you mention for announcing, "hey, I get used with circular references!"  I tend to return a single function to make the negated announcement.

I may (eventually) migrate my use case to the form you mentioned.  In the mean-time, I see value in the pull request since it expands the set of code that Nodefy can operate on.  (Not to mention it would save me some refactoring.)

**Comment by popham** [comment]
Should I interpret your silence on the pull request as a hard 'no'?  If not, then what deficiencies need addressing?

If it's a hard 'no', then I'd appreciate a "won't fix" and closure so that I can move on to contingency plans.

**Comment by popham** [comment]
I've published a fork to `npm` as `nfy` that incorporates the pull request.  Thanks for 98% of the work.
